### PR TITLE
Re-introduce visible member of property descriptions

### PR DESCRIPTION
**Pull request by benfrancis**
Re-introduce visible member of property descriptions, bump ipc-schema and bump version to 1.1.1

This is part of a solution to https://github.com/WebThingsIO/gateway/issues/3038

### CODE REVIEW

**Comment by benfrancis** [comment]
I'm not sure how important it is that those actions failed? Does the action need to pass in order to generate a package that the gateway can use as a dependency, or does it just check out the source from GitHub?

**Comment by arist0v** [comment]
I tested the code with my webtio-hydroqc-addon wich was faulty before, and now it'S working as expected so the fix seem to be OK

**Comment by arist0v** [comment]
The 2 action who failed are related to python 3.5 and 3.6 who are, based on this website: https://endoflife.date/python not supported anymore. so you should probably juste remove them from the workflow and the action should be ok for the 3.7 (who by the way will not be supported in 6 months based on the same website)

depending of the repository configuration, the action may need to pass before the rest could continue.

**Comment by benfrancis** [comment]
Thanks very much for testing that, @arist0v.

> The 2 action who failed are related to python 3.5 and 3.6 who are, based on this website: https://endoflife.date/python not supported anymore

Ah yes, looks like the ubuntu-latest [GitHub runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) can be either Ubuntu 20.04 or Ubuntu 22.04, and the latter ships with minimum Python 3.7.

Our Buster Raspberry Pi image ships with Python 3.7, so hopefully it should be OK to retire the other two.

I've removed the older versions and it seems happy now.

**Review by tim-hellhake — APPROVED** [review]

**Pull request merged**
